import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App + Tailwind</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen max-w-screen-lg mx-auto flex flex-col items-center justify-center">
        <h1 className="text-4xl font-bold">
          Welcome to{" "}
          <a href="https://nextjs.org" className="text-blue-500">
            Next.js
          </a>{" "}
          +{" "}
          <a href="https://tailwindcss.com" className="text-green-700">
            Tailwind
          </a>
          !
        </h1>

        <p>
          Get started by editing <code>pages/index.js</code>
        </p>
      </main>
    </div>
  );
}
